//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function.
func (in *GuardianPolicy) DeepCopyInto(out *GuardianPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function.
func (in *GuardianPolicy) DeepCopy() *GuardianPolicy {
	if in == nil {
		return nil
	}
	out := new(GuardianPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function.
func (in *GuardianPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *GuardianPolicyList) DeepCopyInto(out *GuardianPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GuardianPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function.
func (in *GuardianPolicyList) DeepCopy() *GuardianPolicyList {
	if in == nil {
		return nil
	}
	out := new(GuardianPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function.
func (in *GuardianPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *GuardianPolicySpec) DeepCopyInto(out *GuardianPolicySpec) {
	*out = *in
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	in.Detection.DeepCopyInto(&out.Detection)
	in.Response.DeepCopyInto(&out.Response)
	in.ThreatIntel.DeepCopyInto(&out.ThreatIntel)
	in.SIEM.DeepCopyInto(&out.SIEM)
}

// DeepCopy is an autogenerated deepcopy function.
func (in *GuardianPolicySpec) DeepCopy() *GuardianPolicySpec {
	if in == nil {
		return nil
	}
	out := new(GuardianPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *DetectionConfig) DeepCopyInto(out *DetectionConfig) {
	*out = *in
	if in.EnabledDetectors != nil {
		in, out := &in.EnabledDetectors, &out.EnabledDetectors
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function.
func (in *DetectionConfig) DeepCopy() *DetectionConfig {
	if in == nil {
		return nil
	}
	out := new(DetectionConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *ResponseConfig) DeepCopyInto(out *ResponseConfig) {
	*out = *in
	if in.ApprovedNamespaces != nil {
		in, out := &in.ApprovedNamespaces, &out.ApprovedNamespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ExcludedNamespaces != nil {
		in, out := &in.ExcludedNamespaces, &out.ExcludedNamespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function.
func (in *ResponseConfig) DeepCopy() *ResponseConfig {
	if in == nil {
		return nil
	}
	out := new(ResponseConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *ThreatIntelConfig) DeepCopyInto(out *ThreatIntelConfig) {
	*out = *in
	if in.VirusTotalSecretRef != nil {
		in, out := &in.VirusTotalSecretRef, &out.VirusTotalSecretRef
		*out = new(SecretRef)
		**out = **in
	}
	if in.AbuseIPDBSecretRef != nil {
		in, out := &in.AbuseIPDBSecretRef, &out.AbuseIPDBSecretRef
		*out = new(SecretRef)
		**out = **in
	}
	if in.OTXSecretRef != nil {
		in, out := &in.OTXSecretRef, &out.OTXSecretRef
		*out = new(SecretRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function.
func (in *ThreatIntelConfig) DeepCopy() *ThreatIntelConfig {
	if in == nil {
		return nil
	}
	out := new(ThreatIntelConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *SIEMConfig) DeepCopyInto(out *SIEMConfig) {
	*out = *in
	if in.Splunk != nil {
		in, out := &in.Splunk, &out.Splunk
		*out = new(SplunkConfig)
		**out = **in
	}
	if in.Elastic != nil {
		in, out := &in.Elastic, &out.Elastic
		*out = new(ElasticConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function.
func (in *SIEMConfig) DeepCopy() *SIEMConfig {
	if in == nil {
		return nil
	}
	out := new(SIEMConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *GuardianPolicyStatus) DeepCopyInto(out *GuardianPolicyStatus) {
	*out = *in
	if in.LastDetectionTime != nil {
		in, out := &in.LastDetectionTime, &out.LastDetectionTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function.
func (in *GuardianPolicyStatus) DeepCopy() *GuardianPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(GuardianPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto for SecretRef.
func (in *SecretRef) DeepCopyInto(out *SecretRef) {
	*out = *in
}

// DeepCopy for SecretRef.
func (in *SecretRef) DeepCopy() *SecretRef {
	if in == nil {
		return nil
	}
	out := new(SecretRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto for SplunkConfig.
func (in *SplunkConfig) DeepCopyInto(out *SplunkConfig) {
	*out = *in
	out.TokenRef = in.TokenRef
}

// DeepCopy for SplunkConfig.
func (in *SplunkConfig) DeepCopy() *SplunkConfig {
	if in == nil {
		return nil
	}
	out := new(SplunkConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto for ElasticConfig.
func (in *ElasticConfig) DeepCopyInto(out *ElasticConfig) {
	*out = *in
	out.APIKeyRef = in.APIKeyRef
}

// DeepCopy for ElasticConfig.
func (in *ElasticConfig) DeepCopy() *ElasticConfig {
	if in == nil {
		return nil
	}
	out := new(ElasticConfig)
	in.DeepCopyInto(out)
	return out
}
